wip refactor relu example to aot structure.
Got error: use of undeclared identifier 'TRELU_IMPL'
Need to use latest pto-isa header instead of CANN 8.5.0 default